"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11 06:19:46.718744
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_file", sa.String(length=512), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("exchange_id", sa.String(length=128), nullable=True),
        sa.Column("contract_version", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("stores_upserted", sa.Integer(), nullable=False),
        sa.Column("products_upserted", sa.Integer(), nullable=False),
        sa.Column("documents_accepted", sa.Integer(), nullable=False),
        sa.Column("documents_rejected", sa.Integer(), nullable=False),
        sa.Column("lines_accepted", sa.Integer(), nullable=False),
        sa.Column("lines_rejected", sa.Integer(), nullable=False),
        sa.Column("errors_count", sa.Integer(), nullable=False),
        sa.Column("revenue_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('started', 'success', 'partial', 'failed')", name=op.f("ck_etl_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etl_runs")),
    )
    with op.batch_alter_table("etl_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_etl_runs_exchange_id"), ["exchange_id"], unique=False)
        batch_op.create_index("ix_etl_runs_started_at", ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_etl_runs_status"), ["status"], unique=False)

    op.create_table(
        "model_params",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_params")),
        sa.UniqueConstraint("key", name=op.f("uq_model_params_key")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_source_ref"), ["source_ref"], unique=True)

    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("store_format", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
    )
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stores_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_stores_source_ref"), ["source_ref"], unique=True)

    op.create_table(
        "etl_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=True),
        sa.Column("source_ref", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["etl_runs.id"],
            name=op.f("fk_etl_errors_run_id_etl_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_etl_errors")),
    )
    with op.batch_alter_table("etl_errors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_etl_errors_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_etl_errors_run_id_stage", ["run_id", "stage"], unique=False)

    op.create_table(
        "sale_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.Column("doc_date", sa.Date(), nullable=False),
        sa.Column("doc_number", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("etl_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "doc_type IN ('sale', 'return')", name=op.f("ck_sale_documents_doc_type")
        ),
        sa.ForeignKeyConstraint(
            ["etl_run_id"],
            ["etl_runs.id"],
            name=op.f("fk_sale_documents_etl_run_id_etl_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_sale_documents_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_documents")),
        sa.UniqueConstraint("source_ref", name="uq_sale_documents_source_ref"),
    )
    with op.batch_alter_table("sale_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sale_documents_doc_date"), ["doc_date"], unique=False)
        batch_op.create_index(
            "ix_sale_documents_store_id_doc_date", ["store_id", "doc_date"], unique=False
        )

    op.create_table(
        "sale_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.Column("quantity_milli", sa.BigInteger(), nullable=False),
        sa.Column("revenue_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("cost_accounting_kopecks", sa.BigInteger(), nullable=True),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["sale_documents.id"],
            name=op.f("fk_sale_lines_document_id_sale_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_sale_lines_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
        sa.UniqueConstraint("source_ref", name="uq_sale_lines_source_ref"),
    )
    with op.batch_alter_table("sale_lines", schema=None) as batch_op:
        batch_op.create_index("ix_sale_lines_document_id", ["document_id"], unique=False)
        batch_op.create_index(
            "ix_sale_lines_store_id_sale_date", ["store_id", "sale_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale_lines", schema=None) as batch_op:
        batch_op.drop_index("ix_sale_lines_store_id_sale_date")
        batch_op.drop_index("ix_sale_lines_document_id")

    op.drop_table("sale_lines")
    with op.batch_alter_table("sale_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_sale_documents_store_id_doc_date")
        batch_op.drop_index(batch_op.f("ix_sale_documents_doc_date"))

    op.drop_table("sale_documents")
    with op.batch_alter_table("etl_errors", schema=None) as batch_op:
        batch_op.drop_index("ix_etl_errors_run_id_stage")
        batch_op.drop_index(batch_op.f("ix_etl_errors_run_id"))

    op.drop_table("etl_errors")
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stores_source_ref"))
        batch_op.drop_index(batch_op.f("ix_stores_code"))

    op.drop_table("stores")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_source_ref"))
        batch_op.drop_index(batch_op.f("ix_products_sku"))
        batch_op.drop_index(batch_op.f("ix_products_category"))

    op.drop_table("products")
    op.drop_table("model_params")
    with op.batch_alter_table("etl_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_etl_runs_status"))
        batch_op.drop_index("ix_etl_runs_started_at")
        batch_op.drop_index(batch_op.f("ix_etl_runs_exchange_id"))

    op.drop_table("etl_runs")
    # ### end Alembic commands ###
